login:
  path:     /login
  defaults: { _controller: 'DbaGameBundle:Security:login' }

clear:
  path:     /clear
  defaults: { _controller: 'DbaGameBundle:Security:clear' }

logout:
  path:     /logout

game:
  resource: "@DbaGameBundle/Controller/DefaultController.php"
  type:     rest

game_data:
  resource: "@DbaGameBundle/Controller/DataController.php"
  type:     rest
  prefix: /data

game_account:
  resource: "@DbaGameBundle/Controller/AccountController.php"
  type:     rest
  prefix: /account

game_map:
  resource: "@DbaGameBundle/Controller/MapController.php"
  type:     rest
  prefix: /map
