imports:
  - { resource: parameters.yml }
  - { resource: doctrine.yml }
  - { resource: framework.yml }
  - { resource: swiftmailer.yml }
  - { resource: twig.yml }
  - { resource: rest.yml }
  - { resource: security.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: en

nelmio_api_doc: ~
