doctrine:
  dbal:
    driver:   pdo_pgsql
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "%database_name%"
    user:     "%database_user%"
    password: "%database_password%"
    charset:   UTF8

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    dql:
      numeric_functions:
        GREATEST: DoctrineExtensions\Query\Mysql\Greatest

stof_doctrine_extensions:
  default_locale: en_US
  orm:
    default:
      timestampable: true
