fos_rest:
  serializer:
    serialize_null: true
  body_listener:
    enabled: true
  view:
    view_response_listener:
      force: true
      enabled: true
    formats:
      json: true
  format_listener:
    rules:
      - { path: ^/api, priorities: [ json ], fallback_format: json, prefer_extension: true }
      - { path: ^/admin/css, priorities: [ css ], fallback_format: css, prefer_extension: true }
      - { path: ^/admin, priorities: [ html ], fallback_format: html, prefer_extension: true }

nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['*']
    allow_headers: ['x-csrftoken', 'content-type']
    allow_methods: ['POST', 'GET', 'PUT', 'PATCH', 'DELETE']
    forced_allow_origin_value: false
    hosts: ['localhost', 'jdr-dba.dev', 'rpg-dbadventure.com']
    max_age: 3600
