# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  providers:
    user_db:
      entity: { class: Dba\GameBundle\Entity\Player, property: username }

  role_hierarchy:
    ROLE_MODO: ROLE_PLAYER
    ROLE_ADMIN: ROLE_MODO
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: true
      provider: user_db
      json_login:
        check_path: /api/login
      logout:
        path:   /api/logout
        target: /api/clear

  encoders:
    Dba\GameBundle\Entity\Player: sha512

  access_control:
    - { path: ^/api/account/confirm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/account, roles: ROLE_PLAYER }
    - { path: ^/api/action, roles: ROLE_PLAYER }
    - { path: ^/api/building, roles: ROLE_PLAYER }
    - { path: ^/api/guild, roles: ROLE_PLAYER }
    - { path: ^/api/inbox, roles: ROLE_PLAYER }
    - { path: ^/api/inventory, roles: ROLE_PLAYER }
    - { path: ^/api/magic, roles: ROLE_PLAYER }
    - { path: ^/api/map, roles: ROLE_PLAYER }
    - { path: ^/api/quest, roles: ROLE_PLAYER }

    - { path: ^/admin, roles: ROLE_MODO }
