# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  providers:
    user_db:
      entity: { class: Dba\GameBundle\Entity\Player, property: username }

  role_hierarchy:
    ROLE_MODO: ROLE_PLAYER
    ROLE_ADMIN: ROLE_MODO
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: ~
      provider: user_db
      form_login:
        login_path: /
        check_path: /login
        always_use_default_target_path: true
        default_target_path: /account/dashboard
      logout:
        path:   /logout
        target: /

  encoders:
    Dba\GameBundle\Entity\Player: sha512

  access_control:
    - { path: ^/account, roles: ROLE_PLAYER }
    - { path: ^/action, roles: ROLE_PLAYER }
    - { path: ^/building, roles: ROLE_PLAYER }
    - { path: ^/inbox, roles: ROLE_PLAYER }
    - { path: ^/magic, roles: ROLE_PLAYER }
    - { path: ^/inventory, roles: ROLE_PLAYER }
    - { path: ^/map, roles: ROLE_PLAYER }
    - { path: ^/guild, roles: ROLE_PLAYER }

    - { path: ^/admin, roles: ROLE_MODO }
