#!/bin/bash

function display() {
    if [ -t 1 ]; then
        printf "\e[90m### \e[93m $1 \e[0m\n";
    else
        printf "### $1\n";
    fi
}

function check() {
    local LAST_ERROR=$?
    if [ ${LAST_ERROR} -ne 0 ]; then
        display "/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\"
        display "/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\\Error in last command/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\"
        display "/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\\Return code was ${LAST_ERROR} /!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\"
        display "/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\/!\\"
        exit ${LAST_ERROR}
    fi
}
