<?php

namespace Dba\GameBundle\Repository;

/**
 * DragonBallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DragonBallRepository extends \Doctrine\ORM\EntityRepository
{
}
