<?php

namespace Dba\GameBundle\Repository;

/**
 * NpcObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NpcObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
