<?php

namespace Dba\GameBundle\Repository;

/**
 * PlayerQuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerQuestRepository extends \Doctrine\ORM\EntityRepository
{
}
