<?php

namespace Dba\GameBundle\Repository;

/**
 * QuestObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
