<?php

namespace Dba\GameBundle\Repository;

/**
 * QuestNpcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestNpcRepository extends \Doctrine\ORM\EntityRepository
{
}
