<?php

namespace Dba\GameBundle\Repository;

/**
 * QuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestRepository extends \Doctrine\ORM\EntityRepository
{
}
